### ISSUE TITLE
A couple styling bugs on Participant page

### ISSUE THREAD

**Issue by adowski** [calblueprint/unloop#101]
1. Studio circle thing is kind of off
2. Intake forms aren't side by side (i'm on a 2015 macbook pro if that helps)

![image](https://user-images.githubusercontent.com/43366398/79674401-b54d2c80-8197-11ea-86cd-949f02e5fcc5.png)

**Comment by kwfk** [comment]
same here on Firefox
https://unloop-staging.herokuapp.com/participants/8
![image](https://user-images.githubusercontent.com/9738398/79674422-f8a79b00-8197-11ea-96f7-c276676e408c.png)

**Comment by kwfk** [comment]
https://unloop-staging.herokuapp.com/studio_assessments
![image](https://user-images.githubusercontent.com/9738398/79674473-6358d680-8198-11ea-9d48-56972f013f80.png)
